# Generated by Django 5.2 on 2025-05-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='CNIE',
            field=models.CharField(default='UNKNOWN', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscription',
            name='specialites',
            field=models.CharField(default='UNKNOWN', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
