# Generated by Django 5.2 on 2025-05-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_inscription_cnie_inscription_specialites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='specialites',
            field=models.CharField(max_length=50),
        ),
    ]
