# Generated by Django 5.2 on 2025-04-30 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('presontation_generale', models.TextField()),
                ('loi', models.TextField()),
                ('vedio', models.FileField(blank=True, null=True, upload_to='vedios/')),
                ('Historique', models.TextField()),
                ('Partenaires', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
    ]
